---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mern-auth
  namespace: development
  labels:
    app: mern-auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        apps: mern-auth
    spec:
#Note: key.js need to be added to /mnt/data directory on minikube host for this volume storage method to work
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: mern-auth
          imagePullPolicy: IfNotPresent
#          image: http://localhost:5001/mern-auth:latest
          image: http://192.168.0.158:5001/mern-auth:latest
          ports:
            - containerPort: 3000
              name: "frontend"
            - containerPort: 5000
              name: backend
          volumeMounts:
            - mountPath: "/var/lib/jenkins/workspace/mern_docker/config"
              name: task-pv-storage
