---
apiVersion: v1
kind: Pod
metadata:
  name: mern-auth-jenks-k8s-service
  namespace: development
  labels:
    app: mern-auth-jenks-k8s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        apps: mern-auth-jenks-k8s-service
    spec:
#Note: key.js need to be added to /mnt/data directory on minikube host for this volume storage method to work
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
          claimName: task-pv-claim
      containers:
        - name: mern-auth-jenks-k8s-service
          imagePullPolicy: IfNotPresent
          image: localhost:5001/mern-auth-jenks-k8s_full_stack_app:latest
          ports:
            - containerPort: 3000
              name: "frontend"
            - containerPort: 5000
              name: backend
          volumeMounts:
            - mountPath: "/var/lib/jenkins/workspace/mern_docker/config"
              name: task-pv-storage
