version: '3.3'

services:
    full_stack_app:
      build: .
      volumes:
#       - "/opt/test/docker_test:/app"
#       - "./routes/api:/app"
#        - "./config/:/opt/test/MERN-AUTH-ANSIBLE/config/"
#        - "/home/patrick/Apps/MERN-AUTH-DOCKER/config:/var/lib/jenkins/workspace/mern_docker/config"
      ports:
        - "5000:5000"
        - "3000:3000"
#      expose:
#        - "5000"
#        - "3000"
#        - "3333"
#        - "5555"
#    working_dir: /opt/test/docker_test

#    client:
#      build: .
#      volumes:
#        - "./client:/app"
#      ports:
#        - "3333:3000"
#      expose:
#        - "3000"
##      working_dir:
#      depends_on:
#        - api
