apiVersion: v1
kind: Service
metadata:
  name: mern-auth-jenks-k8s
  namespace: development
spec:
  ports:
    - name: frontend
      port: 3000
    - name: backend
      port: 5000
  type: LoadBalancer
  selector:
    apps: mern-auth-jenks-k8s-service
