apiVersion: v1
kind: Service
metadata:
  name: mern-auth-service
spec:
  selector:
    app: mern-auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
    - protocol: TCP
      port: 5000
      targetPort: 5000
