apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
#  name: mern-auth-service
  name: mern-auth-service
#  labels:
#    name: mern-auth
  namespace: development
#  labels:
#    app: mern-auth
=======
  name: mern-auth-service
>>>>>>> e547b3e77583be3c8de92b6c78317e2fb285a75a
spec:
  selector:
    app: mern-auth
  ports:
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
<<<<<<< HEAD
#    - name: backend
#      protocol: TCP
#      port: 5000
#      targetPort: 5000
  type: NodePort
=======
    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000
>>>>>>> e547b3e77583be3c8de92b6c78317e2fb285a75a
